# Macchina device agent. Allows to access configuration GUI of the OVL remotely.
# https://remote.macchina.io/my-devices/signup

services:
  macchina:
    image: 'docker.io/macchina/device-agent:v2.3.2'
    restart: always

    environment:
      # Domain is specific to your account at macchina.
      - WEBTUNNEL_DOMAIN=[TODO:Replace with Domain!]
      # To get Device ID, first register it at macchina
      - WEBTUNNEL_DEVICE_ID=[TODO: Replace with device id!]
      # Arbitrary name, just for information
      - WEBTUNNEL_DEVICE_NAME=OVL-TEST-DEVICE
      # What host and port number should the requests be redirected to:
      - WEBTUNNEL_HOST=192.168.1.135
      - WEBTUNNEL_HTTP_PORT=4880
      # Reflector URI for the free accounts.
      - WEBTUNNEL_REFLECTOR_URI=https://reflector.my-devices.net/
      #https://remote.macchina.io
      
      # https://reflector.my-devices.net

      # The Passwword is not required for free accouts.
      - WEBTUNNEL_PASSWORD=

    networks:
      ogamma-logger: {}

networks:
  ogamma-logger:
    driver: bridge
