
services:
# Microsoft SQL Server
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-CU15-GDR1-ubuntu-22.04'
    ports:
      - '0.0.0.0:1433:1433'
    hostname: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Ogamma_123 #TODO
    networks:
      - ogamma-logger      
      
networks:
  ogamma-logger: null

